### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Pranav2907** [wangxr0526/Parrot#2]
I am trying to use the inference but in the download_data.py file the link to Parrot_train_in_Reaxy_TotalSyn_Condit folder is missing so that I can place it in output and run the inference to predict temperature the USPTO side is running fine.

**Comment by wangxr0526** [comment]
Thank you for your support of our work. The folder `Parrot/dataset/source_dataset/Reaxys_total_syn_condition_final/` contains some files used for inference. The files in the dataset need to be exported from Reaxys according to the DOI. Due to the commercial nature of Reaxys, we are unable to directly share this constructed dataset. Please refer to `Parrot/preprocess_script/reaxys_script/reaxys_totalsyn_condition.md` and follow the steps to construct it.
